### ISSUE TITLE
Found duplicate project

### ISSUE THREAD

**Issue by JGordonx** [Montreal-Analytics/dbt-snowflake-utils#18]
Since the update i get this error now
Found duplicate project "dbt_utils". This occurs when a dependency has the same project name as some other dependency. Code: 10006

These are my packages
packages:
  - package: fishtown-analytics/audit_helper
    version: [">=0.3.0"]
  - package: fishtown-analytics/dbt_utils
    version: [">=0.6.6"]
  - package: fishtown-analytics/logging
    version: [">=0.4.2"]
  - package: fishtown-analytics/dbt_external_tables
    version: [">=0.6.2"]
  - package: Montreal-Analytics/snowflake_utils
    version: [">=0.2.0"]

**Comment by MartinGuindon** [comment]
Hi @JGordonx , sorry I missed this issue due to improperly configured notifications. Since this is an old issue, I assume you resolved it since then. I'll close the issue, but this error usually happens if one of the package is trying to load the dbt_utils package via git instead of the package syntax. I know snowflake_utils is setup properly, so I'd assume (but didn't check) that one of these packages is trying to load dbt-utils via git.
