### ISSUE TITLE
Add additional Snowflake clean-up macros found in the wild

### ISSUE THREAD

**Issue by boxysean** [Montreal-Analytics/dbt-snowflake-utils#19]
Hey Montreal Analytics folks!

I saw some Snowflake clean-up macros from my colleagues floating around internal discussions and thought they might be a natural fit for the `snowflake_utils` package, [see here](https://github.com/patkearns10/dbt_workspace/tree/master/dbt/macros/snowflake_utils/cleanup). I believe they originate from @randypitcherii by way of @patkearns10.

The macros:

- clean_workspace
- drop_deprecated_tables
- drop_deprecated_tables
- drop_old_relations

What do you think, do they fit inside the package?

**Comment by MartinGuindon** [comment]
Hi @boxysean, sorry for the late answer, my GitHub notifications for this repo were not properly configured and I missed these.

I'm a bit torn because while they may be extremely useful, they're not Snowflake specific actions. The vision I had for this package was to provide a set of useful macros that are leveraging Snowflake specific features (warehouse resize, clone schema, blue/green deploys, etc.), and potentially macros that are required as part of these operations.

Dropping deprecated tables or old relations could be made cross-db compatible and might fit more in a dbt-utils type of package?

Thoughts?
